### ISSUE TITLE
Missing some files required by tests

### ISSUE THREAD

**Issue by igoumiri** [LLNL/SSAPy#7]
The `data` submodule is missing some files required by tests. I added them in https://github.com/LLNL/SSAPy-Data/pull/1 but I'm opening this issue for tracking (since the submodule will need to be bumped).

**Comment by aperloff** [comment]
@igoumiri Check out https://github.com/LLNL/SSAPy/pull/2. I want to use Git LFS to store these files in the SSAPy repo rather than having them external to this repo and in a submodule. Even if these files are in a submodule, they are too big to be uploaded to GitHub and would need to be split into pieces for storage on GitHub and recombined before being used on the users computer.
